public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        int a = 50000;
        System.out.println("a = " + a);
        byte b = 100;
        System.out.println("b = " + b);
        short c = 30000;
        System.out.println("c = " + c);
        long d = 3000000000L;
        System.out.println("d = " + d);
        float e = 1.5f;
        System.out.println("e = " + e);
        double f = 40.5;
        System.out.println("f = " + f);
        System.out.println("Задача 2");
        float e2 = 27.12f;
        System.out.println("e2 = " + e2);
        double f2 = 2.786;
        System.out.println("f2 = " + f2);
        long d2 = 987678965549L;
        System.out.println("d2 = " + d2);
        short c2 = 569;
        System.out.println("c2 = " + c2);
        int a2 = 27897;
        System.out.println("a2 = " + a2);
        short c3 = -159;
        System.out.println("c3 = " + c3);
        byte b2 = 67;
        System.out.println("b2 = " + b2);
        System.out.println("Задача 3");
        byte firstClass = 23;
        System.out.println("в классе у Людмилы Павловны " + firstClass + " ученика");
        byte secondClass = 27;
        System.out.println("в классе у Анны Сергеевны " + secondClass + " учеников");
        byte thirdClass = 30;
        System.out.println("в классе у Екатерины Сергеевны " + thirdClass + " учеников");
        int allStudents = firstClass + secondClass + thirdClass;
        System.out.println("всего " + allStudents + " учеников в трех классах");
        int allSheets = 480;
        System.out.println("всего " + allSheets + " листов бумаги");
        int studentSheets = allSheets/allStudents;
        System.out.println("На каждого ученика рассчитано " + studentSheets + " листов бумаги");
        System.out.println("Задача 4");
        int bottleIn2Minuts = 16;
        System.out.println("Произведено " + bottleIn2Minuts + " бутылок за 2 минуты");
        int bottleIn1Minuts = bottleIn2Minuts/2;
        System.out.println("Произведено " + bottleIn1Minuts + " бутылок за 1 минуту");
        int bottleIn20Minuts =  bottleIn1Minuts * 20;
        System.out.println("Произведено " + bottleIn20Minuts + " бутылок за 20 минут");
        int bottleIn1hour =  bottleIn20Minuts * 3;
        System.out.println("Произведено " + bottleIn1hour + " бутылок за 1 час");
        int bottleIn24hour =  bottleIn1hour * 24;
        System.out.println("Произведено " + bottleIn24hour + " бутылок за 24 часа");
        int bottleIn3days =  bottleIn24hour * 3;
        System.out.println("Произведено " + bottleIn3days + " бутылок за 3 дня");
        int bottleIn1month =  bottleIn3days * 10;
        System.out.println("Произведено " + bottleIn1month + " бутылок за месяц");
        System.out.println("Задача 5");
        byte bottlePaint = 120;
        System.out.println("Всего " +  bottlePaint + " банок краски");
        byte whitePaint = 2;
        System.out.println("Всего на покраску одного класса нужно " +  whitePaint + " банки белой краски");
        byte brownPaint = 4;
        System.out.println("Всего на покраску одного класса нужно " +  brownPaint + " банки оричневой краски");
        int totalClass = (bottlePaint / (whitePaint + brownPaint));
        System.out.println("Всего покрашено " +  totalClass + " классов");
        int whitePaintNeed = totalClass * whitePaint;
        int brownPaintNeed = totalClass * brownPaint;
        System.out.println("В школе, где " + totalClass + " классов, нужно " + whitePaintNeed + " банок белой краски и " + brownPaintNeed + " банок коричневой краски");
        System.out.println("Задача 6");
        int bananaWeight = 80;
        int bananaNeeds = 5;
        int fiveBananaWeight = bananaWeight * bananaNeeds;
        int milkWeightInGramm = 105;
        int milkneed = 200/100;
        int milkWeightNeed = milkWeightInGramm * milkneed;
        int iceCream = 100;
        int iceCreamNeed = 2;
        int iceCreamWeight = iceCream * iceCreamNeed;
        int eggWeight = 70;
        int eggNeed = 4;
        int eggWeightNeed = eggWeight * eggNeed;
        float totalBreakfastWeight = fiveBananaWeight + milkWeightNeed + iceCreamWeight + eggWeightNeed;
        System.out.println("общий вес завтрака " +  totalBreakfastWeight + " грамм");
        int Kg = 1000;
        float totalBreakfastWeightInKg = totalBreakfastWeight/ Kg;
        System.out.println("общий вес завтрака " +  totalBreakfastWeightInKg + " килограмм");
        System.out.println("Задача 7");
        int kgInGr = 7 * 1000;
        int grInDay = 250;
        int grInDay2 = 500;
        int dayForMinimumWeight = kgInGr/grInDay;
        int dayForMaximumWeight = kgInGr/grInDay2;
        double averageValue = (dayForMinimumWeight+dayForMaximumWeight)/2D;
        System.out.println("необходимо " +  dayForMinimumWeight + " дней при потере спортсменом 250 грамм в день");
        System.out.println("необходимо " +  kgInGr/grInDay2 + " дней при потере спортсменом 500 грамм в день");
        System.out.println("необходимо в среднем " +  averageValue + " дней");
        System.out.println("Задача 8");
        int salaryMasha = 67760;
        int salaryDenis = 83690;
        int salaryKristina = 76230;
        int persentSalaryMasha = salaryMasha/10;
        int persentSalaryDenis = salaryDenis/10;
        int persentSalaryKristina = salaryMasha/10;
        int newSalaryMasha = salaryMasha + persentSalaryMasha;
        int newSalaryDenis = salaryDenis + persentSalaryDenis;
        int newSalaryKristina = salaryKristina + persentSalaryKristina;
        int oldSalaryMasha = (newSalaryMasha - salaryMasha) * 12;
        int oldSalaryDenis = (newSalaryDenis - salaryDenis) * 12;
        int oldSalaryKristina = (newSalaryKristina - salaryKristina) * 12;
        System.out.println("Маша теперь получает "  + newSalaryMasha + " рублей. Годовой доход вырос на " + oldSalaryMasha  + " рублей");
        System.out.println("Денис теперь получает "  + newSalaryDenis + " рублей. Годовой доход вырос на " + oldSalaryDenis  + " рублей");
        System.out.println("денис теперь получает "  + newSalaryKristina + " рублей. Годовой доход вырос на " + oldSalaryKristina  + " рублей");
    }
}